const orderSchema=new mongoose.Schema({
    name: String,
    email: String,
    phone: String,
    address: String,
    city: String,
    state: String,
    pincode: String,
    country: String,
    gender: String,
    dob: String,
    role: String,
    status: String,
    image: String,
    product: String,
    price: String,
    quantity: String,
    total: String,
    });
    const Order=mongoose.model('Order', orderSchema);